ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster

WORKDIR /app

COPY . /app
RUN yarn

WORKDIR /app/packages/client
RUN yarn && yarn build:ssr && yarn build

WORKDIR /app/packages/server
RUN yarn

EXPOSE $SERVER_PORT

CMD ["yarn", "dev"]
